security:
    # TODO : check : bcrypt plutôt que sha512 : symfony bonnes pratiques => empêche le rainbow table attack
    encoders:
        CGG\ConferenceBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    # TODO : Pour l'instant connection qu'avec le username (à mettre unique dans la base), ajouter la connection avec l'email.
        database_users:
            entity:
                class: CGGConferenceBundle:User

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        security_admin:
            pattern:  ^/
            provider:   database_users
            anonymous: ~
            form_login:
                login_path:   cgg_conference_login
                check_path:   cgg_conference_login_check
            logout:
                path:   cgg_conference_logout
                target:   cgg_conference_home

    access_control:
        - { path: ^/createConference, roles: ROLE_USER}
        - { path: ^/liste-nouvelle-conferences, roles: ROLE_ADMIN}

    acl:
       connection: default