<?php

namespace CGG\ConferenceBundle\Repository;

use CGG\ConferenceBundle\Entity\Conference;
use Doctrine\ORM\EntityManager;

/**
 * ConferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferenceRepository
{
    protected $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    public function save(Conference $conference){
        $this->entityManager->persist($conference);
        $this->entityManager->flush();
    }
    public function findAll(){
       return $this->entityManager->getRepository('CGGConferenceBundle:Conference')->findAll();
    }

    public function find($idConference){
        return $this->entityManager->find("CGGConferenceBundle:Conference", $idConference);

    }
}
