<?php

namespace CGG\ConferenceBundle\Repository;

use CGG\ConferenceBundle\Entity\Conference;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * ConferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferenceRepository extends EntityRepository
{
    protected $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    public function save(Conference $conference){
        $this->entityManager->persist($conference);
        $this->entityManager->flush();
    }
    public function findAll(){
        $connection = $this->entityManager->getConnection();
        return $connection->fetchAll("SELECT * FROM Conference;");
    }
}
