<?php

namespace CGG\ConferenceBundle\Repository;

use CGG\ConferenceBundle\Entity\Content;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository
{
    protected $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    public function findByPageId($idPage){
        $query = $this->entityManager->getRepository('CGGConferenceBundle:Content')->createQueryBuilder('c')
            ->where('c.page = ' . $idPage)
            ->getQuery();
        return $query->getResult();
    }
}
