<?php

namespace CGG\ConferenceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HeadBandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeadBandRepository extends EntityRepository
{
}
