<?php

namespace CGG\ConferenceBundle\Repository;

use CGG\ConferenceBundle\Entity\Page;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    protected $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    public function findByConferenceId($idConference){
        $query = $this->entityManager->getRepository('CGGConferenceBundle:Page')->createQueryBuilder('p')
                ->where('p.page_conference_id = ' . $idConference)
                ->getQuery();
        return $query->getResult();
    }
}
