<?php

namespace CGG\ConferenceBundle\Repository;

use CGG\ConferenceBundle\Entity\User;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    protected $entityManager;

    public function __construct(EntityManager $entityManager){
        $this->entityManager = $entityManager;
    }

    public function save(User $user){
        $this->entityManager->persist($user);
        $this->entityManager->flush();
    }
}
